DROP DATABASE IF EXISTS delawaredb_test;
CREATE DATABASE delawaredb_test;
USE delawaredb_test;

CREATE TABLE `company` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `BANKACCOUNTNR` bigint DEFAULT NULL,
  `CUSTOMERSTART` date DEFAULT NULL,
  `ISACTIVE` tinyint(1) DEFAULT '0',
  `LOGO` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `SECTOR` varchar(255) DEFAULT NULL,
  `VATNUMBER` varchar(255) DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `NUMBER` varchar(255) DEFAULT NULL,
  `STREET` varchar(255) DEFAULT NULL,
  `ZIPCODE` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `PHONENUMBER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=78 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `account` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ROLE` int DEFAULT NULL,
  `company_id` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ACCOUNT_company_id` (`company_id`),
  CONSTRAINT `FK_ACCOUNT_company_id` FOREIGN KEY (`company_id`) REFERENCES `company` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `company_known_companies` (
  `company_id` bigint NOT NULL,
  `known_company_id` bigint NOT NULL,
  PRIMARY KEY (`company_id`,`known_company_id`),
  KEY `FK_company_known_companies_known_company_id` (`known_company_id`),
  CONSTRAINT `FK_company_known_companies_company_id` FOREIGN KEY (`company_id`) REFERENCES `company` (`ID`),
  CONSTRAINT `FK_company_known_companies_known_company_id` FOREIGN KEY (`known_company_id`) REFERENCES `company` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `company_paymentoptions` (
  `Company_ID` bigint DEFAULT NULL,
  `PAYMENTOPTIONS` varchar(255) DEFAULT NULL,
  KEY `FK_Company_PAYMENTOPTIONS_Company_ID` (`Company_ID`),
  CONSTRAINT `FK_Company_PAYMENTOPTIONS_Company_ID` FOREIGN KEY (`Company_ID`) REFERENCES `company` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `company_update_requests` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NEWBANKACCOUNTNR` bigint DEFAULT NULL,
  `NEWCUSTOMEREMAIL` varchar(255) DEFAULT NULL,
  `NEWCUSTOMERPASSWORD` varchar(255) DEFAULT NULL,
  `NEWCUSTOMERSTART` date DEFAULT NULL,
  `NEWLOGO` varchar(255) DEFAULT NULL,
  `NEWNAME` varchar(255) DEFAULT NULL,
  `NEWSECTOR` varchar(255) DEFAULT NULL,
  `NEWSUPPLIEREMAIL` varchar(255) DEFAULT NULL,
  `NEWSUPPLIERPASSWORD` varchar(255) DEFAULT NULL,
  `NEWVATNUMBER` varchar(255) DEFAULT NULL,
  `OLDVATNUMBER` varchar(255) DEFAULT NULL,
  `REQUESTDATE` date DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `NUMBER` varchar(255) DEFAULT NULL,
  `STREET` varchar(255) DEFAULT NULL,
  `ZIPCODE` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `PHONENUMBER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `companyupdaterequest_newpaymentoptions` (
  `CompanyUpdateRequest_ID` bigint DEFAULT NULL,
  `NEWPAYMENTOPTIONS` varchar(255) DEFAULT NULL,
  KEY `CmpnypdtRequestNEWPAYMENTOPTIONSCmpnypdteRequestID` (`CompanyUpdateRequest_ID`),
  CONSTRAINT `CmpnypdtRequestNEWPAYMENTOPTIONSCmpnypdteRequestID` FOREIGN KEY (`CompanyUpdateRequest_ID`) REFERENCES `company_update_requests` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DATE` date DEFAULT NULL,
  `NOTIFICATIONSTATUS` varchar(255) DEFAULT NULL,
  `NOTIFICATIONTYPE` varchar(255) DEFAULT NULL,
  `ORDERID` varchar(255) DEFAULT NULL,
  `TEXT` varchar(255) DEFAULT NULL,
  `COMPANYID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_NOTIFICATION_COMPANYID` (`COMPANYID`),
  CONSTRAINT `FK_NOTIFICATION_COMPANYID` FOREIGN KEY (`COMPANYID`) REFERENCES `company` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PRICE` int DEFAULT NULL,
  `PRODUCTAVAILABILITY` varchar(255) DEFAULT NULL,
  `PRODUCTCATEGORYID` varchar(255) DEFAULT NULL,
  `PRODUCTID` varchar(255) DEFAULT NULL,
  `PRODUCTUNITOFMEASUREID` varchar(255) DEFAULT NULL,
  `SYNCID` int DEFAULT NULL,
  `FROMCOMPANY_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUCT_FROMCOMPANY_ID` (`FROMCOMPANY_ID`),
  CONSTRAINT `FK_PRODUCT_FROMCOMPANY_ID` FOREIGN KEY (`FROMCOMPANY_ID`) REFERENCES `company` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=389 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_table` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CURRENCY` varchar(255) DEFAULT NULL,
  `DATE` varchar(255) DEFAULT NULL,
  `LASTPAYMENTREMINDER` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `NETAMOUNT` double DEFAULT NULL,
  `ORDERDATETIME` date DEFAULT NULL,
  `ORDERID` varchar(255) DEFAULT NULL,
  `ORDERREFERENCE` varchar(255) DEFAULT NULL,
  `ORDERSTATUS` int DEFAULT NULL,
  `PAYMENTSTATUS` int DEFAULT NULL,
  `TAXAMOUNT` double DEFAULT NULL,
  `TOTALAMOUNT` double DEFAULT NULL,
  `FROMCOMPANY_ID` bigint DEFAULT NULL,
  `TOCOMPANY_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_order_table_FROMCOMPANY_ID` (`FROMCOMPANY_ID`),
  KEY `FK_order_table_TOCOMPANY_ID` (`TOCOMPANY_ID`),
  CONSTRAINT `FK_order_table_FROMCOMPANY_ID` FOREIGN KEY (`FROMCOMPANY_ID`) REFERENCES `company` (`ID`),
  CONSTRAINT `FK_order_table_TOCOMPANY_ID` FOREIGN KEY (`TOCOMPANY_ID`) REFERENCES `company` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3648 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `orderitem` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `INSTOCK` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ORDERID` int DEFAULT NULL,
  `ORDERITEMID` int DEFAULT NULL,
  `QUANTITY` int DEFAULT NULL,
  `SYNCID` int DEFAULT NULL,
  `TOTAL` decimal(38,0) DEFAULT NULL,
  `UNITOFMEASUREID` varchar(255) DEFAULT NULL,
  `UNITPRICE` decimal(38,0) DEFAULT NULL,
  `FROMORDER_ID` bigint DEFAULT NULL,
  `PRODUCT_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ORDERITEM_PRODUCT_ID` (`PRODUCT_ID`),
  KEY `FK_ORDERITEM_FROMORDER_ID` (`FROMORDER_ID`),
  CONSTRAINT `FK_ORDERITEM_FROMORDER_ID` FOREIGN KEY (`FROMORDER_ID`) REFERENCES `order_table` (`ID`),
  CONSTRAINT `FK_ORDERITEM_PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `product` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5250 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
