-- Error code: P3017
-- https://stackoverflow.com/questions/76321912/error-p3017-when-i-run-npx-prisma-command

-- CreateTable
CREATE TABLE `account` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(255) NULL,
    `PASSWORD` VARCHAR(255) NULL,
    `ROLE` INTEGER NULL,
    `company_id` BIGINT NULL,

    INDEX `FK_ACCOUNT_company_id`(`company_id`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `company` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `BANKACCOUNTNR` BIGINT NULL,
    `CUSTOMERSTART` DATE NULL,
    `ISACTIVE` BOOLEAN NULL DEFAULT false,
    `LOGO` VARCHAR(255) NULL,
    `NAME` VARCHAR(255) NULL,
    `SECTOR` VARCHAR(255) NULL,
    `VATNUMBER` VARCHAR(255) NULL,
    `CITY` VARCHAR(255) NULL,
    `COUNTRY` VARCHAR(255) NULL,
    `NUMBER` VARCHAR(255) NULL,
    `STREET` VARCHAR(255) NULL,
    `ZIPCODE` VARCHAR(255) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `PHONENUMBER` VARCHAR(255) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `company_known_companies` (
    `company_id` BIGINT NOT NULL,
    `known_company_id` BIGINT NOT NULL,

    INDEX `FK_company_known_companies_known_company_id`(`known_company_id`),
    PRIMARY KEY (`company_id`, `known_company_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `company_paymentoptions` (
    `Company_ID` BIGINT NULL,
    `PAYMENTOPTIONS` VARCHAR(255) NULL,

    INDEX `FK_Company_PAYMENTOPTIONS_Company_ID`(`Company_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `company_update_requests` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NEWBANKACCOUNTNR` BIGINT NULL,
    `NEWCUSTOMEREMAIL` VARCHAR(255) NULL,
    `NEWCUSTOMERPASSWORD` VARCHAR(255) NULL,
    `NEWCUSTOMERSTART` DATE NULL,
    `NEWLOGO` VARCHAR(255) NULL,
    `NEWNAME` VARCHAR(255) NULL,
    `NEWSECTOR` VARCHAR(255) NULL,
    `NEWSUPPLIEREMAIL` VARCHAR(255) NULL,
    `NEWSUPPLIERPASSWORD` VARCHAR(255) NULL,
    `NEWVATNUMBER` VARCHAR(255) NULL,
    `OLDVATNUMBER` VARCHAR(255) NULL,
    `REQUESTDATE` DATE NULL,
    `CITY` VARCHAR(255) NULL,
    `COUNTRY` VARCHAR(255) NULL,
    `NUMBER` VARCHAR(255) NULL,
    `STREET` VARCHAR(255) NULL,
    `ZIPCODE` VARCHAR(255) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `PHONENUMBER` VARCHAR(255) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `companyupdaterequest_newpaymentoptions` (
    `CompanyUpdateRequest_ID` BIGINT NULL,
    `NEWPAYMENTOPTIONS` VARCHAR(255) NULL,

    INDEX `CmpnypdtRequestNEWPAYMENTOPTIONSCmpnypdteRequestID`(`CompanyUpdateRequest_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `order_table` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CURRENCY` VARCHAR(255) NULL,
    `DATE` VARCHAR(255) NULL,
    `LASTPAYMENTREMINDER` VARCHAR(255) NULL,
    `NAME` VARCHAR(255) NULL,
    `NETAMOUNT` VARCHAR(255) NULL,
    `ORDERDATETIME` DATE NULL,
    `ORDERID` VARCHAR(255) NULL,
    `ORDERREFERENCE` VARCHAR(255) NULL,
    `ORDERSTATUS` INTEGER NULL,
    `PAYMENTSTATUS` INTEGER NULL,
    `TAXAMOUNT` VARCHAR(255) NULL,
    `TOTALAMOUNT` VARCHAR(255) NULL,
    `FROMCOMPANY_ID` BIGINT NULL,
    `TOCOMPANY_ID` BIGINT NULL,

    INDEX `FK_order_table_FROMCOMPANY_ID`(`FROMCOMPANY_ID`),
    INDEX `FK_order_table_TOCOMPANY_ID`(`TOCOMPANY_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `orderitem` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `INSTOCK` VARCHAR(255) NULL,
    `NAME` VARCHAR(255) NULL,
    `ORDERID` INTEGER NULL,
    `ORDERITEMID` INTEGER NULL,
    `QUANTITY` INTEGER NULL,
    `SYNCID` INTEGER NULL,
    `TOTAL` DECIMAL(38, 0) NULL,
    `UNITOFMEASUREID` VARCHAR(255) NULL,
    `UNITPRICE` DECIMAL(38, 0) NULL,
    `FROMORDER_ID` BIGINT NULL,
    `PRODUCT_ID` BIGINT NULL,

    INDEX `FK_ORDERITEM_FROMORDER_ID`(`FROMORDER_ID`),
    INDEX `FK_ORDERITEM_PRODUCT_ID`(`PRODUCT_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `product` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `PRODUCTAVAILABILITY` VARCHAR(255) NULL,
    `PRODUCTCATEGORYID` VARCHAR(255) NULL,
    `PRODUCTID` VARCHAR(255) NULL,
    `PRODUCTUNITOFMEASUREID` VARCHAR(255) NULL,
    `SYNCID` INTEGER NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `account` ADD CONSTRAINT `FK_ACCOUNT_company_id` FOREIGN KEY (`company_id`) REFERENCES `company`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `company_known_companies` ADD CONSTRAINT `FK_company_known_companies_company_id` FOREIGN KEY (`company_id`) REFERENCES `company`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `company_known_companies` ADD CONSTRAINT `FK_company_known_companies_known_company_id` FOREIGN KEY (`known_company_id`) REFERENCES `company`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `company_paymentoptions` ADD CONSTRAINT `FK_Company_PAYMENTOPTIONS_Company_ID` FOREIGN KEY (`Company_ID`) REFERENCES `company`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `companyupdaterequest_newpaymentoptions` ADD CONSTRAINT `CmpnypdtRequestNEWPAYMENTOPTIONSCmpnypdteRequestID` FOREIGN KEY (`CompanyUpdateRequest_ID`) REFERENCES `company_update_requests`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `order_table` ADD CONSTRAINT `FK_order_table_FROMCOMPANY_ID` FOREIGN KEY (`FROMCOMPANY_ID`) REFERENCES `company`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `order_table` ADD CONSTRAINT `FK_order_table_TOCOMPANY_ID` FOREIGN KEY (`TOCOMPANY_ID`) REFERENCES `company`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `orderitem` ADD CONSTRAINT `FK_ORDERITEM_FROMORDER_ID` FOREIGN KEY (`FROMORDER_ID`) REFERENCES `order_table`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `orderitem` ADD CONSTRAINT `FK_ORDERITEM_PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `product`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

